[[redirects]]
  from = "/docs/SDK/accessControlConditionExamples"
  to = "/docs/AccessControlConditions/evmBasicExamples"
  status = 302
  force = false

[[redirects]]
  from = "docs/accessControlModal"
  to = "/docs/shareModal"
  status = 302
  force = false



